server:
  port: 9092

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/rayco
  application:
    name: rayco-api

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/rayco-db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
    properties:
      hibernate:
        default_schema: rayco_schema
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect

keycloak:
  url: http://localhost:8082
  realm: rayco
  grant-type: password
  client-id: rayco-client
  client-secret: Z81IJHYbW4pCmT0FdardiCy6MFFprx99
  admin:
    credentials:
      email: admin@gmail.com
      password: admin


feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full


